<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Book;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{

    public function addNewBook($data){
        $book = new Book();
        $book->setName($data['name']);
        $book->setAuthor($data['author']);
        $book->setYearPublished($data['year']);
        $book->setGender($data['gender']);
        $book->setDescription($data['description']);
        $this->_em->persist($book);
        $this->_em->flush();
        return 1;
    }

    public function editBook($data){
        $book = $this->find($data['id']);
        if(empty($book)){
            return 0;
        }
        $book->setName($data['name']);
        $book->setAuthor($data['author']);
        $book->setYearPublished($data['year']);
        $book->setGender($data['gender']);
        $book->setDescription($data['description']);
        $this->_em->persist($book);
        $this->_em->flush();
        return 1;
    }

    public function deleteBook($id){
        $book = $this->find($id);
        if(empty($book)){
            return 0;
        }
        $this->_em->remove($book);
        $this->_em->flush();
        return 1;
    }
}
